# Gitpod configuration for Move development with Movement Network
tasks:
  - name: Setup Movement Development Environment
    init: |
      # Install Rust (required for Move)
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      
      # Install prerequisites
      sudo apt-get update
      sudo apt-get install -y git cmake libssl-dev libclang-dev
      
      # Clone Movement core repo and build CLI
      git clone https://github.com/movementlabsxyz/aptos-core.git
      cd aptos-core
      
      # Install all prerequisites using automatic script
      ./scripts/dev_setup.sh
      source ~/.cargo/env
      
      # Build the Movement CLI tool
      cargo build -p movement
      
      # Move executable to PATH
      sudo cp target/debug/movement /usr/local/bin/
      cd ..
      
      # Verify Movement CLI installation
      movement --help
      
      # Initialize Movement profile for development
      movement init --network custom --rest-url https://aptos.testnet.porto.movementlabs.xyz/v1 --faucet-url https://fund.testnet.porto.movementlabs.xyz
      
      # Navigate to Move project directory
      cd my-onchain-bio/move
      
      # Show project structure
      echo "=== Project Structure ==="
      ls -la
      echo ""
      echo "=== Move.toml Contents ==="
      cat Move.toml
      echo ""
      echo "=== Move Source Files ==="
      ls -la sources/
      
    command: |
      echo "🎉 Movement development environment is ready!"
      echo "📁 You're now in the Move project directory: $(pwd)"
      echo ""
      echo "🚀 Available Movement commands:"
      echo "  - movement move build    # Build your Move project"
      echo "  - movement move test     # Run tests"
      echo "  - movement move publish  # Publish contract to Movement blockchain"
      echo "  - movement move run      # Call functions on blockchain"
      echo "  - movement account balance # Check account balance"
      echo ""
      echo "💡 Start by running: movement move build"
      echo ""
      echo "🔗 Movement Network: https://aptos.testnet.porto.movementlabs.xyz"
      echo "💰 Faucet: https://fund.testnet.porto.movementlabs.xyz
    openIn: "bottom"
    openMode: "tab-after"

ports:
  - port: 8080
    onOpen: "open-preview"
    visibility: "private"
    name: "Movement Development Server"
    description: "Port for Movement blockchain development tools and interfaces"
    protocol: "http"

vscode:
  extensions:
    - rust-lang.rust-analyzer

workspaceLocation: "my-onchain-bio/move"

# Environment variables for Movement development
env:
  MOVEMENT_NETWORK: "https://aptos.testnet.porto.movementlabs.xyz/v1"
  MOVEMENT_FAUCET: "https://fund.testnet.porto.movementlabs.xyz"
  RUST_BACKTRACE: "1" 